<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <RootNamespace>Coffee_Machine</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="arrow.jpg" />
    <None Remove="arrowleft.jpg" />
    <None Remove="card_cup_dark.png" />
    <None Remove="check.png" />
    <None Remove="dark_cup.png" />
    <None Remove="home_dark.png" />
    <None Remove="keyboard_backspace_white_right.png" />
    <None Remove="sugar.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="arrow.jpg" />
    <Resource Include="arrowleft.jpg" />
    <Resource Include="card_cup_dark.png" />
    <Resource Include="check.png" />
    <Resource Include="dark_cup.png" />
    <Resource Include="home_dark.png" />
    <Resource Include="keyboard_backspace_white_right.png" />
    <Resource Include="sugar.png" />
  </ItemGroup>

</Project>
